-- The patient file, the clinic module's first table (C3 of
-- context/plans/20260923-the-first-clinic-module-patients-queue-appointments.md).
-- Identity plus notes and nothing else: no debt, no fee, no fund as payer.
-- It is its own table rather than a differently typed `customers` row
-- because the plan's paper test found the identity columns would fit and the
-- money columns would not.
--
-- In the one shared migration list (D5 of the core-and-modules plan): a shop
-- install carries this table empty, the same way a clinic install carries
-- the shop's.
--
-- Additive. No existing table is rebuilt and no row is moved, so the revert
-- is a DROP.

CREATE TABLE patients (
    -- A UUID v7 as its 36-character text, generated by the clinic service
    -- and never by SQLite: the cloud relay and the patient app both need an
    -- id that stays unique across machines, and v7's leading timestamp keeps
    -- the text sorting in creation order. The length CHECK refuses an
    -- integer or a truncated id reaching the column by any other road.
    id            TEXT PRIMARY KEY NOT NULL CHECK (length(id) = 36),
    -- The kernel's tenant, whatever the trade (the plan's "The tenant").
    -- RESTRICT, with every other table a person's record sits in.
    shop_id       INTEGER NOT NULL REFERENCES shops(id) ON DELETE RESTRICT,
    -- Both required and never blank: the list is read by name and a file
    -- with no name is a file nobody can find again. Two patients may share
    -- both names, so there is no UNIQUE.
    first_name    TEXT NOT NULL CHECK (length(trim(first_name)) > 0),
    last_name     TEXT NOT NULL CHECK (length(trim(last_name)) > 0),
    -- Optional: a file is opened at the desk before anyone asks.
    sex           TEXT CHECK (sex IS NULL OR sex IN ('female', 'male')),
    -- ISO date text (YYYY-MM-DD). `date(x) IS x` holds only for a real
    -- calendar day written in exactly that shape, so '2026-02-30' (which
    -- date() rolls over to March), '1990-1-5' and a date with a time on it
    -- are all refused here as well as in the service. `IS` and not `=`:
    -- date() of text it cannot read is NULL, `NULL = x` is NULL, and a CHECK
    -- that comes out NULL passes.
    date_of_birth TEXT CHECK (date_of_birth IS NULL OR date(date_of_birth) IS date_of_birth),
    -- Digits with an optional leading '+'; the service strips the spaces,
    -- dots and dashes a person types between them so a search by number
    -- finds it however it was typed.
    phone         TEXT,
    -- Free text, the cabinet's own notes on the patient.
    notes         TEXT,
    -- NULL while the file is live. Archived files leave the search but are
    -- never deleted: the queue and the book will point at them.
    archived_at   TEXT,
    -- The shop's clock (services::clock), stamped by the service on every
    -- write. No DEFAULT on purpose: CURRENT_TIMESTAMP is UTC and would put a
    -- file opened at 00:30 in Algiers on the day before.
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
) STRICT;

-- The list: one shop's files by surname then first name, which is the order
-- the service reads them in. A search is a substring match, which no b-tree
-- index can serve, so these two keep the ordered read and an exact-number
-- lookup cheap rather than pretending to speed up the LIKE.
CREATE INDEX idx_patients_shop_name ON patients (shop_id, last_name, first_name);
CREATE INDEX idx_patients_shop_phone ON patients (shop_id, phone);
