[package]
name = "dzpos-desktop"
version.workspace = true
edition.workspace = true
default-run = "dzpos-desktop"

[dependencies]
dzpos-core = { path = "../../../crates/core" }
serde = { workspace = true, features = ["derive"] }
dirs = "6.0"
tauri = { version = "2", features = ["devtools"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
