/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as BarcodesRouteImport } from "./routes/barcodes"
import { Route as EndOfDayRouteImport } from "./routes/end-of-day"
import { Route as ExpensesRouteImport } from "./routes/expenses"
import { Route as ProductsRouteImport } from "./routes/products"
import { Route as PurchaseOrdersRouteImport } from "./routes/purchase-orders"
import { Route as SuppliersRouteImport } from "./routes/suppliers"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const BarcodesRoute = BarcodesRouteImport.update({
  id: "/barcodes",
  path: "/barcodes",
  getParentRoute: () => rootRouteImport,
} as any)
const EndOfDayRoute = EndOfDayRouteImport.update({
  id: "/end-of-day",
  path: "/end-of-day",
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: "/expenses",
  path: "/expenses",
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: "/purchase-orders",
  path: "/purchase-orders",
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: "/suppliers",
  path: "/suppliers",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/barcodes": typeof BarcodesRoute
  "/end-of-day": typeof EndOfDayRoute
  "/expenses": typeof ExpensesRoute
  "/products": typeof ProductsRoute
  "/purchase-orders": typeof PurchaseOrdersRoute
  "/suppliers": typeof SuppliersRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/barcodes": typeof BarcodesRoute
  "/end-of-day": typeof EndOfDayRoute
  "/expenses": typeof ExpensesRoute
  "/products": typeof ProductsRoute
  "/purchase-orders": typeof PurchaseOrdersRoute
  "/suppliers": typeof SuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/barcodes": typeof BarcodesRoute
  "/end-of-day": typeof EndOfDayRoute
  "/expenses": typeof ExpensesRoute
  "/products": typeof ProductsRoute
  "/purchase-orders": typeof PurchaseOrdersRoute
  "/suppliers": typeof SuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/barcodes"
    | "/end-of-day"
    | "/expenses"
    | "/products"
    | "/purchase-orders"
    | "/suppliers"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/barcodes"
    | "/end-of-day"
    | "/expenses"
    | "/products"
    | "/purchase-orders"
    | "/suppliers"
  id:
    | "__root__"
    | "/"
    | "/barcodes"
    | "/end-of-day"
    | "/expenses"
    | "/products"
    | "/purchase-orders"
    | "/suppliers"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarcodesRoute: typeof BarcodesRoute
  EndOfDayRoute: typeof EndOfDayRoute
  ExpensesRoute: typeof ExpensesRoute
  ProductsRoute: typeof ProductsRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  SuppliersRoute: typeof SuppliersRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/barcodes": {
      id: "/barcodes"
      path: "/barcodes"
      fullPath: "/barcodes"
      preLoaderRoute: typeof BarcodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/end-of-day": {
      id: "/end-of-day"
      path: "/end-of-day"
      fullPath: "/end-of-day"
      preLoaderRoute: typeof EndOfDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/expenses": {
      id: "/expenses"
      path: "/expenses"
      fullPath: "/expenses"
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/products": {
      id: "/products"
      path: "/products"
      fullPath: "/products"
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/purchase-orders": {
      id: "/purchase-orders"
      path: "/purchase-orders"
      fullPath: "/purchase-orders"
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/suppliers": {
      id: "/suppliers"
      path: "/suppliers"
      fullPath: "/suppliers"
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarcodesRoute: BarcodesRoute,
  EndOfDayRoute: EndOfDayRoute,
  ExpensesRoute: ExpensesRoute,
  ProductsRoute: ProductsRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
