/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuditRouteImport } from "./routes/audit"
import { Route as CustomersRouteImport } from "./routes/customers"
import { Route as DashboardRouteImport } from "./routes/dashboard"
import { Route as DocumentsRouteImport } from "./routes/documents"
import { Route as ExpensesRouteImport } from "./routes/expenses"
import { Route as KitRouteImport } from "./routes/kit"
import { Route as ProductsRouteImport } from "./routes/products"
import { Route as PurchasesRouteImport } from "./routes/purchases"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as SuppliersRouteImport } from "./routes/suppliers"
import { Route as TillRouteImport } from "./routes/till"
import { Route as CustomersIdRouteImport } from "./routes/customers_.$id"
import { Route as PurchasesIdRouteImport } from "./routes/purchases_.$id"
import { Route as PurchasesNewRouteImport } from "./routes/purchases_.new"
import { Route as SettingsIndexRouteImport } from "./routes/settings.index"
import { Route as SettingsAboutRouteImport } from "./routes/settings.about"
import { Route as SettingsAppearanceRouteImport } from "./routes/settings.appearance"
import { Route as SettingsBackupsRouteImport } from "./routes/settings.backups"
import { Route as SettingsDataRouteImport } from "./routes/settings.data"
import { Route as SettingsPhonesRouteImport } from "./routes/settings.phones"
import { Route as SettingsPrintingRouteImport } from "./routes/settings.printing"
import { Route as SettingsRegimeRouteImport } from "./routes/settings.regime"
import { Route as SettingsShopRouteImport } from "./routes/settings.shop"
import { Route as SettingsUsersRouteImport } from "./routes/settings.users"
import { Route as SuppliersIdRouteImport } from "./routes/suppliers_.$id"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: "/documents",
  path: "/documents",
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: "/expenses",
  path: "/expenses",
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: "/kit",
  path: "/kit",
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: "/purchases",
  path: "/purchases",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: "/suppliers",
  path: "/suppliers",
  getParentRoute: () => rootRouteImport,
} as any)
const TillRoute = TillRouteImport.update({
  id: "/till",
  path: "/till",
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: "/customers_/$id",
  path: "/customers/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesIdRoute = PurchasesIdRouteImport.update({
  id: "/purchases_/$id",
  path: "/purchases/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: "/purchases_/new",
  path: "/purchases/new",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBackupsRoute = SettingsBackupsRouteImport.update({
  id: "/backups",
  path: "/backups",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: "/data",
  path: "/data",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPhonesRoute = SettingsPhonesRouteImport.update({
  id: "/phones",
  path: "/phones",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrintingRoute = SettingsPrintingRouteImport.update({
  id: "/printing",
  path: "/printing",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRegimeRoute = SettingsRegimeRouteImport.update({
  id: "/regime",
  path: "/regime",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsShopRoute = SettingsShopRouteImport.update({
  id: "/shop",
  path: "/shop",
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => SettingsRoute,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: "/suppliers_/$id",
  path: "/suppliers/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/audit": typeof AuditRoute
  "/customers": typeof CustomersRoute
  "/dashboard": typeof DashboardRoute
  "/documents": typeof DocumentsRoute
  "/expenses": typeof ExpensesRoute
  "/kit": typeof KitRoute
  "/products": typeof ProductsRoute
  "/purchases": typeof PurchasesRoute
  "/settings": typeof SettingsRouteWithChildren
  "/suppliers": typeof SuppliersRoute
  "/till": typeof TillRoute
  "/customers/$id": typeof CustomersIdRoute
  "/purchases/$id": typeof PurchasesIdRoute
  "/purchases/new": typeof PurchasesNewRoute
  "/settings/about": typeof SettingsAboutRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/backups": typeof SettingsBackupsRoute
  "/settings/data": typeof SettingsDataRoute
  "/settings/phones": typeof SettingsPhonesRoute
  "/settings/printing": typeof SettingsPrintingRoute
  "/settings/regime": typeof SettingsRegimeRoute
  "/settings/shop": typeof SettingsShopRoute
  "/settings/users": typeof SettingsUsersRoute
  "/suppliers/$id": typeof SuppliersIdRoute
  "/settings/": typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/audit": typeof AuditRoute
  "/customers": typeof CustomersRoute
  "/dashboard": typeof DashboardRoute
  "/documents": typeof DocumentsRoute
  "/expenses": typeof ExpensesRoute
  "/kit": typeof KitRoute
  "/products": typeof ProductsRoute
  "/purchases": typeof PurchasesRoute
  "/suppliers": typeof SuppliersRoute
  "/till": typeof TillRoute
  "/customers/$id": typeof CustomersIdRoute
  "/purchases/$id": typeof PurchasesIdRoute
  "/purchases/new": typeof PurchasesNewRoute
  "/settings/about": typeof SettingsAboutRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/backups": typeof SettingsBackupsRoute
  "/settings/data": typeof SettingsDataRoute
  "/settings/phones": typeof SettingsPhonesRoute
  "/settings/printing": typeof SettingsPrintingRoute
  "/settings/regime": typeof SettingsRegimeRoute
  "/settings/shop": typeof SettingsShopRoute
  "/settings/users": typeof SettingsUsersRoute
  "/suppliers/$id": typeof SuppliersIdRoute
  "/settings": typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/audit": typeof AuditRoute
  "/customers": typeof CustomersRoute
  "/dashboard": typeof DashboardRoute
  "/documents": typeof DocumentsRoute
  "/expenses": typeof ExpensesRoute
  "/kit": typeof KitRoute
  "/products": typeof ProductsRoute
  "/purchases": typeof PurchasesRoute
  "/settings": typeof SettingsRouteWithChildren
  "/suppliers": typeof SuppliersRoute
  "/till": typeof TillRoute
  "/customers_/$id": typeof CustomersIdRoute
  "/purchases_/$id": typeof PurchasesIdRoute
  "/purchases_/new": typeof PurchasesNewRoute
  "/settings/about": typeof SettingsAboutRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/backups": typeof SettingsBackupsRoute
  "/settings/data": typeof SettingsDataRoute
  "/settings/phones": typeof SettingsPhonesRoute
  "/settings/printing": typeof SettingsPrintingRoute
  "/settings/regime": typeof SettingsRegimeRoute
  "/settings/shop": typeof SettingsShopRoute
  "/settings/users": typeof SettingsUsersRoute
  "/suppliers_/$id": typeof SuppliersIdRoute
  "/settings/": typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/audit"
    | "/customers"
    | "/dashboard"
    | "/documents"
    | "/expenses"
    | "/kit"
    | "/products"
    | "/purchases"
    | "/settings"
    | "/suppliers"
    | "/till"
    | "/customers/$id"
    | "/purchases/$id"
    | "/purchases/new"
    | "/settings/about"
    | "/settings/appearance"
    | "/settings/backups"
    | "/settings/data"
    | "/settings/phones"
    | "/settings/printing"
    | "/settings/regime"
    | "/settings/shop"
    | "/settings/users"
    | "/suppliers/$id"
    | "/settings/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/audit"
    | "/customers"
    | "/dashboard"
    | "/documents"
    | "/expenses"
    | "/kit"
    | "/products"
    | "/purchases"
    | "/suppliers"
    | "/till"
    | "/customers/$id"
    | "/purchases/$id"
    | "/purchases/new"
    | "/settings/about"
    | "/settings/appearance"
    | "/settings/backups"
    | "/settings/data"
    | "/settings/phones"
    | "/settings/printing"
    | "/settings/regime"
    | "/settings/shop"
    | "/settings/users"
    | "/suppliers/$id"
    | "/settings"
  id:
    | "__root__"
    | "/"
    | "/audit"
    | "/customers"
    | "/dashboard"
    | "/documents"
    | "/expenses"
    | "/kit"
    | "/products"
    | "/purchases"
    | "/settings"
    | "/suppliers"
    | "/till"
    | "/customers_/$id"
    | "/purchases_/$id"
    | "/purchases_/new"
    | "/settings/about"
    | "/settings/appearance"
    | "/settings/backups"
    | "/settings/data"
    | "/settings/phones"
    | "/settings/printing"
    | "/settings/regime"
    | "/settings/shop"
    | "/settings/users"
    | "/suppliers_/$id"
    | "/settings/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  ExpensesRoute: typeof ExpensesRoute
  KitRoute: typeof KitRoute
  ProductsRoute: typeof ProductsRoute
  PurchasesRoute: typeof PurchasesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SuppliersRoute: typeof SuppliersRoute
  TillRoute: typeof TillRoute
  CustomersIdRoute: typeof CustomersIdRoute
  PurchasesIdRoute: typeof PurchasesIdRoute
  PurchasesNewRoute: typeof PurchasesNewRoute
  SuppliersIdRoute: typeof SuppliersIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/audit": {
      id: "/audit"
      path: "/audit"
      fullPath: "/audit"
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/customers": {
      id: "/customers"
      path: "/customers"
      fullPath: "/customers"
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/documents": {
      id: "/documents"
      path: "/documents"
      fullPath: "/documents"
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/expenses": {
      id: "/expenses"
      path: "/expenses"
      fullPath: "/expenses"
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/kit": {
      id: "/kit"
      path: "/kit"
      fullPath: "/kit"
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/products": {
      id: "/products"
      path: "/products"
      fullPath: "/products"
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/purchases": {
      id: "/purchases"
      path: "/purchases"
      fullPath: "/purchases"
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/suppliers": {
      id: "/suppliers"
      path: "/suppliers"
      fullPath: "/suppliers"
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/till": {
      id: "/till"
      path: "/till"
      fullPath: "/till"
      preLoaderRoute: typeof TillRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/customers_/$id": {
      id: "/customers_/$id"
      path: "/customers/$id"
      fullPath: "/customers/$id"
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/purchases_/$id": {
      id: "/purchases_/$id"
      path: "/purchases/$id"
      fullPath: "/purchases/$id"
      preLoaderRoute: typeof PurchasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/purchases_/new": {
      id: "/purchases_/new"
      path: "/purchases/new"
      fullPath: "/purchases/new"
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/": {
      id: "/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/about": {
      id: "/settings/about"
      path: "/about"
      fullPath: "/settings/about"
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/appearance": {
      id: "/settings/appearance"
      path: "/appearance"
      fullPath: "/settings/appearance"
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/backups": {
      id: "/settings/backups"
      path: "/backups"
      fullPath: "/settings/backups"
      preLoaderRoute: typeof SettingsBackupsRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/data": {
      id: "/settings/data"
      path: "/data"
      fullPath: "/settings/data"
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/phones": {
      id: "/settings/phones"
      path: "/phones"
      fullPath: "/settings/phones"
      preLoaderRoute: typeof SettingsPhonesRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/printing": {
      id: "/settings/printing"
      path: "/printing"
      fullPath: "/settings/printing"
      preLoaderRoute: typeof SettingsPrintingRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/regime": {
      id: "/settings/regime"
      path: "/regime"
      fullPath: "/settings/regime"
      preLoaderRoute: typeof SettingsRegimeRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/shop": {
      id: "/settings/shop"
      path: "/shop"
      fullPath: "/settings/shop"
      preLoaderRoute: typeof SettingsShopRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/settings/users": {
      id: "/settings/users"
      path: "/users"
      fullPath: "/settings/users"
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    "/suppliers_/$id": {
      id: "/suppliers_/$id"
      path: "/suppliers/$id"
      fullPath: "/suppliers/$id"
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsBackupsRoute: typeof SettingsBackupsRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsPhonesRoute: typeof SettingsPhonesRoute
  SettingsPrintingRoute: typeof SettingsPrintingRoute
  SettingsRegimeRoute: typeof SettingsRegimeRoute
  SettingsShopRoute: typeof SettingsShopRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsBackupsRoute: SettingsBackupsRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsPhonesRoute: SettingsPhonesRoute,
  SettingsPrintingRoute: SettingsPrintingRoute,
  SettingsRegimeRoute: SettingsRegimeRoute,
  SettingsShopRoute: SettingsShopRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  ExpensesRoute: ExpensesRoute,
  KitRoute: KitRoute,
  ProductsRoute: ProductsRoute,
  PurchasesRoute: PurchasesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SuppliersRoute: SuppliersRoute,
  TillRoute: TillRoute,
  CustomersIdRoute: CustomersIdRoute,
  PurchasesIdRoute: PurchasesIdRoute,
  PurchasesNewRoute: PurchasesNewRoute,
  SuppliersIdRoute: SuppliersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
