// The landing page ships Comptoir only: a visitor chooses nothing
// (context/plans/20260911-landing-page.md, L0), so this emits one `:root`
// block and the RTL font swap from the *resolved* `theme` object, not the
// four per-theme blocks packages/design/src/css.ts's toCss() emits for the
// app's theme switcher.
//
// astro.config.ts's dzpos-tokens integration calls this and writes the
// result to src/styles/tokens.css on every `astro dev` / `astro build` /
// `astro check`. That file is gitignored (see .gitignore), so there is no
// generated file to go stale and no separate regeneration step to remember.

import { rtl, theme } from "@dzpos/design";

const { surface, text, border, ...color } = theme.colors;

const lines = (prefix: string, group: Readonly<Record<string, string>>): string[] =>
  Object.entries(group).map(([key, value]) => `  --${prefix}${key}: ${value};`);

const pxLines = (prefix: string, group: Readonly<Record<string, number>>): string[] =>
  Object.entries(group).map(([key, value]) => `  --${prefix}${key}: ${value}px;`);

// `rtl.sans` is a raw semantic token (packages/design/src/semantic.ts), not a
// resolved string; it happens to always be a literal font stack, but the
// check below is what keeps that an assertion instead of an assumption.
const rtlSans = rtl.sans;
if (rtlSans.kind !== "literal") {
  throw new Error("@dzpos/design's rtl.sans is no longer a literal font stack");
}

export const renderTokensCss = (): string =>
  [
    "/* Generated by apps/landing/src/lib/tokens.ts from @dzpos/design.",
    "   Not committed (see .gitignore): astro.config.ts's dzpos-tokens",
    "   integration writes this file fresh on every dev/build/check run.",
    "   Comptoir only, on purpose: no per-theme block, no switcher. */",
    "",
    ":root {",
    [
      ...lines("color-", color),
      ...lines("surface-", surface),
      ...lines("text-", text),
      ...lines("border-", border),
      ...pxLines("space-", theme.space),
      ...pxLines("radius-", theme.radius),
      ...lines("shadow-", theme.shadow),
      ...lines("font-", theme.fontFamily),
      ...pxLines("text-", theme.fontSize),
      ...pxLines("", theme.layout),
    ].join("\n"),
    "}",
    "",
    '[dir="rtl"] {',
    `  --font-sans: ${rtlSans.value};`,
    "}",
    "",
  ].join("\n");
