use super::Gate;
use dzpos_core::services::permissions::Permission;

/// Every mutating route this API answers, and the reads the module doc names
/// that carry the shop's lists out of it, with what each will want.
///
/// Sorted by path, which is how `lib.rs` lists its routes, so the two read
/// side by side.
pub const ROUTE_GATES: &[Gate] = &[
    Gate {
        method: "GET",
        path: "/audit-log",
        permission: Some(Permission::SeeAuditLog),
        why: "the log of sensitive actions across the shop; the owner's alone (services::permissions, M4 T7)",
    },
    Gate {
        method: "POST",
        path: "/auth/login",
        permission: None,
        why: "signing in is how a role comes to exist; gating it on one would be a lock with its key inside",
    },
    Gate {
        method: "POST",
        path: "/auth/logout",
        permission: None,
        why: "anybody who is signed in may stop being, and a sign-out gated on a role is a screen nobody can leave",
    },
    Gate {
        method: "POST",
        path: "/auth/first-setup",
        permission: None,
        why: "the one door into a shop nobody has ever signed into; services::users::claim_first_owner is the whole rule and it shuts itself the moment any credential in the shop exists, so no permission decides who may call it, only that rule does",
    },
    Gate {
        method: "POST",
        path: "/pairing/claim",
        permission: None,
        why: "the phone trades a QR's 60s pairing token for a device token; the pairing token itself is the credential, not a session, so no permission decides who may call it, only whether that token is still live and unused",
    },
    Gate {
        method: "POST",
        path: "/pairing/qr",
        permission: Some(Permission::EditSettings),
        why: "only an owner or manager shows the QR that pairs a phone on the shop floor (M6, docs/roadmap.md); EditSettings is the permission managers hold, and the same gate lists and revokes devices",
    },
    Gate {
        method: "GET",
        path: "/pairing/devices",
        permission: Some(Permission::EditSettings),
        why: "the settings screen lists paired phones; same gate as the QR that created them, and the same audit that revoking one writes",
    },
    Gate {
        method: "POST",
        path: "/pairing/devices/{id}/revoke",
        permission: Some(Permission::EditSettings),
        why: "revoking a phone is the same control as pairing one, and the audit row it writes is the only record the shop has that the phone is no longer trusted",
    },
    Gate {
        method: "GET",
        path: "/backups",
        permission: Some(Permission::EditSettings),
        why: "the list of copies of the shop's whole file, with the day each was taken; it is read by the settings block that takes and restores them and belongs with the two writes beside it (M4 closing review, 2026-09-11)",
    },
    Gate {
        method: "POST",
        path: "/backups",
        permission: Some(Permission::EditSettings),
        why: "a backup is taken from the settings screen and is the shop's whole file; the block it sits in is the settings one",
    },
    Gate {
        method: "POST",
        path: "/backups/{name}/restore",
        permission: Some(Permission::EditSettings),
        why: "a restore replaces every row the shop has; it belongs with the settings it is reached from",
    },
    Gate {
        method: "POST",
        path: "/customers",
        permission: Some(Permission::EditFiches),
        why: "a customer fiche is a card the shop keeps on somebody it deals with",
    },
    Gate {
        method: "PUT",
        path: "/customers/{id}",
        permission: Some(Permission::EditFiches),
        why: "the same fiche, and a body carrying a credit limit is the fiche too",
    },
    Gate {
        method: "POST",
        path: "/customers/{id}/payments",
        permission: None,
        why: "taking money a customer owes over the counter is a till job; it is the debt side of ringing a sale up",
    },
    Gate {
        method: "POST",
        path: "/customers/{id}/adjustments",
        permission: Some(Permission::CorrectLedger),
        why: "correcting what a customer owes is a ledger the ordinary flow does not write (M2 carry-in)",
    },
    Gate {
        method: "GET",
        path: "/dashboard",
        permission: Some(Permission::SeeReports),
        why: "the figures, the top-ten cards and the margin line are the reports SeeReports's own doc names; a cashier has no business on this screen at all (M4 T5 review, 2026-09-11)",
    },
    Gate {
        method: "GET",
        path: "/dashboard/series",
        permission: Some(Permission::SeeReports),
        why: "the chart behind the same dashboard, read separately by the same screen; same permission as the page it draws on (M4 T5 review, 2026-09-11)",
    },
    Gate {
        method: "GET",
        path: "/expenses",
        permission: Some(Permission::SeeReports),
        why: "every expense the shop has booked in a month, with its total: what the shop spends is the shop's standing, and a cashier who may not read the dashboard may not read the ledger the dashboard sums (M4 closing review, 2026-09-11)",
    },
    Gate {
        method: "GET",
        path: "/cash",
        permission: Some(Permission::SeeReports),
        why: "cash in, cash out and card in over a day or a month, which is the dashboard's cash figure asked for directly; same reasoning and same permission as the page (M4 closing review, 2026-09-11)",
    },
    Gate {
        method: "POST",
        path: "/expenses",
        permission: Some(Permission::CommitMoney),
        why: "money out of the drawer, the same way a supplier payment is (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "POST",
        path: "/import/products/dry-run",
        permission: Some(Permission::ExportAndImport),
        why: "an import rewrites prices in bulk from a USB stick (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "POST",
        path: "/import/products",
        permission: Some(Permission::ExportAndImport),
        why: "the same workbook as the dry run, and this is the call that actually rewrites the prices",
    },
    Gate {
        method: "GET",
        path: "/import/products/template",
        permission: Some(Permission::ExportAndImport),
        why: "the blank workbook the import screen hands out: column headings and one made-up example row, carrying none of the shop's own data. It is gated because it is the import screen's own file and a cashier has no business on that screen, not because it walks anything out; /export/products is the route that does that (reason corrected in the M4 closing review, 2026-09-11)",
    },
    Gate {
        method: "GET",
        path: "/export/customers",
        permission: Some(Permission::ExportAndImport),
        why: "the whole customer list on a USB stick, names and debts included (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "GET",
        path: "/export/products",
        permission: Some(Permission::ExportAndImport),
        why: "the whole catalogue with its cost prices (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "GET",
        path: "/export/sales",
        permission: Some(Permission::ExportAndImport),
        why: "every sale the shop ever rang up (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "GET",
        path: "/export/suppliers",
        permission: Some(Permission::ExportAndImport),
        why: "the whole supplier list and what is owed to each (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "POST",
        path: "/labels/sheet",
        permission: None,
        why: "a label prints a name, a price and a barcode a customer can already read off the shelf, and a cashier relabelling a shelf is who needs it (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "POST",
        path: "/products",
        permission: Some(Permission::EditFiches),
        why: "a product's fiche: price, name, barcode, category",
    },
    Gate {
        method: "PUT",
        path: "/products/{id}",
        permission: Some(Permission::EditFiches),
        why: "the same fiche: a price, a name, a barcode or a category changed on a product the shop already stocks",
    },
    Gate {
        method: "GET",
        path: "/purchases",
        permission: Some(Permission::SeeCostAndMargin),
        why: "the order list carries nothing but what the shop pays its suppliers (col_extra_costs, col_unit_cost, col_landed_cost); unlike products, no till flow reads it, so the whole route is gated rather than a field redacted (M4 T5 review, 2026-09-11)",
    },
    Gate {
        method: "GET",
        path: "/purchases/{id}",
        permission: Some(Permission::SeeCostAndMargin),
        why: "the same order, one row at a time; same reasoning and same permission as the list (M4 T5 review, 2026-09-11)",
    },
    Gate {
        method: "POST",
        path: "/purchases",
        permission: Some(Permission::CommitMoney),
        why: "an order commits the shop's money (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "POST",
        path: "/purchases/{id}/receipts",
        permission: Some(Permission::CommitMoney),
        why: "a receipt is what turns the order into what the shop owes (M3 carry-in)",
    },
    Gate {
        method: "POST",
        path: "/purchases/{id}/returns",
        permission: Some(Permission::CorrectLedger),
        why: "a return lowers what the shop owes (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "POST",
        path: "/purchases/{id}/cancel",
        permission: Some(Permission::CorrectLedger),
        why: "undoing an order is the purchase side of undoing a document",
    },
    Gate {
        method: "POST",
        path: "/purchases/{id}/close-short",
        permission: Some(Permission::CorrectLedger),
        why: "a write-off lowers what the shop owes (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "POST",
        path: "/sales",
        permission: Some(Permission::Sell),
        why: "ringing a sale up, the one thing every role may do; named rather than left blank because it is a permission and not an absence of one",
    },
    Gate {
        method: "POST",
        path: "/sales/{id}/print",
        permission: Some(Permission::Sell),
        why: "print through desktop (M6 T6): the same ticket bytes the till just rang up, spooled beside the shop file and optionally pushed to TCP 9100; every role that may sell may print",
    },
    Gate {
        method: "POST",
        path: "/sales/{id}/avoir",
        permission: Some(Permission::CorrectLedger),
        why: "an avoir undoes a document already handed to a customer (M2 carry-in, 2026-09-09)",
    },
    Gate {
        method: "POST",
        path: "/sales/{id}/cancel",
        permission: Some(Permission::CorrectLedger),
        why: "the same, and this one voids the document outright (M2 carry-in, 2026-09-09)",
    },
    Gate {
        method: "PUT",
        path: "/settings/store",
        permission: Some(Permission::EditSettings),
        why: "the seller block every ticket and every facture prints, and the identifiers a facture is refused without",
    },
    Gate {
        method: "POST",
        path: "/settings/discount-threshold",
        permission: Some(Permission::EditSettings),
        why: "how much a cashier may take off a basket before a manager has to say yes; raising it quietly is the same as handing out the discount permission (M4 T6, 2026-09-11)",
    },
    Gate {
        method: "POST",
        path: "/settings/regime",
        permission: Some(Permission::EditSettings),
        why: "the régime fiscal sits inside EditSettings, which a manager holds; splitting it out is the next question if Samir wants it owner-only (services::permissions says so too)",
    },
    Gate {
        method: "PUT",
        path: "/settings/theme",
        permission: None,
        why: "cosmetic, not money and not stock, so it stays open to everybody unless a shop asks otherwise (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "PUT",
        path: "/settings/facture-layout",
        permission: Some(Permission::EditSettings),
        why: "which layout the shop's factures print in is not the theme beside it: the theme changes a screen and this changes the paper a customer is handed and a comptable files, so it sits with the other settings a manager holds (2026-09-17)",
    },
    Gate {
        method: "PUT",
        path: "/settings/print-lang",
        permission: Some(Permission::EditSettings),
        why: "the language every fiscal paper prints in is the same kind of decision as the facture layout beside it, not the theme: it changes what a customer is handed and what a comptable files, so a cashier does not choose it (plan a-print-language-the-shop-keeps, 2026-09-20)",
    },
    Gate {
        method: "POST",
        path: "/stock/recount",
        permission: Some(Permission::CorrectLedger),
        why: "a recount rewrites a cached quantity on hand from the ledger (M3 carry-in, 2026-09-10; routes/stock.rs carried the TODO)",
    },
    Gate {
        method: "GET",
        path: "/suppliers",
        permission: Some(Permission::SeeCostAndMargin),
        why: "the list carries each supplier's balance, which is what the shop owes for goods it has not paid for yet; the buying side is the same side the purchase list sits on and it is gated whole for the same reason, no till flow reads it (M4 closing review, 2026-09-11)",
    },
    Gate {
        method: "GET",
        path: "/suppliers/{id}/ledger",
        permission: Some(Permission::SeeCostAndMargin),
        why: "one supplier's account in full, every invoice and payment behind the balance; same reasoning and same permission as the list (M4 closing review, 2026-09-11)",
    },
    Gate {
        method: "POST",
        path: "/suppliers",
        permission: Some(Permission::EditFiches),
        why: "a supplier's fiche is a card the shop keeps, kept by the same hand as a product's",
    },
    Gate {
        method: "PUT",
        path: "/suppliers/{id}",
        permission: Some(Permission::EditFiches),
        why: "the same fiche, and the closing branch of it: a body carrying `active: false` closes a fiche through the same rule the close route uses (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "POST",
        path: "/suppliers/{id}/close",
        permission: Some(Permission::EditFiches),
        why: "closing a fiche, named beside the PUT that does it the other way (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "POST",
        path: "/suppliers/{id}/payments",
        permission: Some(Permission::CommitMoney),
        why: "money out to a supplier (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "POST",
        path: "/suppliers/{id}/adjustments",
        permission: Some(Permission::CorrectLedger),
        why: "correcting what the shop owes a supplier (M3 carry-in, 2026-09-10)",
    },
    Gate {
        method: "GET",
        path: "/support-bundle",
        permission: Some(Permission::EditSettings),
        why: "a zip the shop sends to whoever is fixing something, reached from the settings screen and gated the same way the backups block beside it is (M5 T3); its own doc names why it carries no customer, product, price or document and an audit row still travels with it, the same as an export's, because the file is on its way out of the shop even though what is in it never is",
    },
    Gate {
        method: "POST",
        path: "/till/shifts",
        permission: Some(Permission::OpenAndCloseTill),
        why: "opening a drawer with what is in it; all three roles hold the permission (plan till-shifts-a-float-and-a-count ruling 10, 2026-09-20), because the person who counts a drawer is the person standing at it and a cashier who cannot open their own till cannot start a day. Named rather than left blank for the reason POST /sales is: it is a permission and not an absence of one",
    },
    Gate {
        method: "GET",
        path: "/till/shifts/{id}",
        permission: Some(Permission::SeeReports),
        why: "one shift with what that person took over its window and what the shop expects them to be holding: a report a manager runs the floor off, and not the audit log, which is the owner's alone (docs/features.md §5). A cashier reads their own open drawer through GET /till/shifts/open, which names nobody and carries no row (plan till-shifts-a-float-and-a-count T4, 2026-09-21)",
    },
    Gate {
        method: "POST",
        path: "/till/shifts/{id}/close",
        permission: Some(Permission::OpenAndCloseTill),
        why: "counting the drawer and closing it, the other half of opening it and the same permission. The coarse half of a pair: one route serves both a cashier counting their own and somebody counting a drawer that was walked away from, so whose drawer it is is decided in services::shifts::close, which asks for Permission::CloseAnotherPersonsTill when the closer is not the opener (ruling 10). A row here cannot make that call, because it is a fact about the row and not about the path",
    },
    Gate {
        method: "GET",
        path: "/users",
        permission: Some(Permission::ManageUsers),
        why: "who the shop's staff are; services::permissions::can's own doc says a manager answers like an owner on everything except this and the audit log, so the list itself is the owner's read and not an ordinary one",
    },
    Gate {
        method: "POST",
        path: "/users",
        permission: Some(Permission::ManageUsers),
        why: "adding a fiche to the staff list is what ManageUsers is named for",
    },
    Gate {
        method: "POST",
        path: "/users/{id}/pin",
        permission: Some(Permission::ManageUsers),
        why: "giving a fiche its first PIN or resetting a forgotten one; the owner's alone, and nothing here ever shows the PIN it replaces because there is not one to show",
    },
    Gate {
        method: "POST",
        path: "/users/{id}/password",
        permission: Some(Permission::ManageUsers),
        why: "the same for a password (M6 T8): an office credential, owner's alone, and the session rule mirrors the PIN's — resetting your own keeps you signed in, every other session for that name is ended",
    },
    Gate {
        method: "POST",
        path: "/users/{id}/deactivate",
        permission: Some(Permission::ManageUsers),
        why: "switching a fiche off; the last-owner and self refusals are T0's, enforced on the row (services::users::deactivate)",
    },
    Gate {
        method: "POST",
        path: "/users/{id}/reactivate",
        permission: Some(Permission::ManageUsers),
        why: "switching a fiche back on, the same permission as switching it off",
    },
];
